webProject/urls.py
from django.contrib import admin
from django.urls import path, include
from main_app import views 

urlpatterns = [
    path('', views.home_page, name='home'),
    path('timetable/', views.timetable_page, name='timetable'),
    path('timetable/get-matches/', views.get_stored_matches_view, name='get_stored_matches'),
    path('user/', views.user_profile, name='user'),
    path('user/get-matches/<int:user_id>', views.user_matches_view, name='user_matches'),
    path('user/edit-profile/', views.user_edit_profile, name='user_edit_profile'),
    path('tournaments/', views.tournaments_page, name='tournaments'),
    path('tournaments/reg-in-tour', views.register_to_tournament, name='register_to_tour'),
    path('tournaments/check-register/', views.check_register, name='check_register'),
    path('tournaments/start-new/', views.start_new_tour_view, name='start_new_tour'),
    path('tournaments/get-next-match/<int:group_id>', views.get_next_match_view, name='get_next_match'),
    path('tournaments/check-permissions/', views.get_user_permissions, name='get_user_permissions'),
    path('tournaments/get-stored-matches/', views.get_stored_matches_view, name='get_stored_matches'),
    path('tournaments/save-match/<uuid:match_id>/', views.save_match_view, name='save_match'),
    path('tournaments/shift-matches-time/', views.shift_matches_view, name='shift_matches'),
    path('ratings/', views.ratings_page, name='ratings'),
    path('ratings/get-competitors/', views.get_competitors_view, name='get_competitors'),
    path('admin/', admin.site.urls, name='admin:index'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/', views.login_view, name='login'),
    path('login/password', views.password_view, name='password'),
    path('register/', views.register_view, name='register'),
    path('bot/<int:user_id>', views.get_chatID_view, name='get_chatID'),
    path('logout/', views.logout_view, name='logout'),
    
]

main_app/models.py
import uuid
from django.utils import timezone
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User


GENDER_TYPE = (
    ('M', 'мужской'),
    ('W', 'женский')
)

TEAM_ROLE = (
    ('forward','нападающий'),
    ('defender', 'защитник'),
    ('goalkeeper','вратарь'),
    ('referee','судья'),
    ('coach','тренер'),
)

CATEGORY_TYPE = (
    ('новичок','новичок'),
    ('любитель', 'любитель'),
    ('III юношеский','III юношеский'),
    ('II юношеский','II юношеский'),
    ('I юношеский','I юношеский'),
    ('III спортивный','III спортивный'),
    ('II спортивный','II спортивный'),
    ('I спортивный','I спортивный'),
    ('КМС','КМС'),
    ('ГР','ГР'),
    ('МСМК','МСМК')
)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True,)
    fullname = models.CharField('ФИО', max_length=200)
    email = models.CharField(max_length=100)
    mobile_phone = models.CharField('Телефон', max_length=20)
    gender = models.CharField('Пол', choices=GENDER_TYPE, max_length=20)
    age = models.IntegerField('Возраст', null=True) 
    category = models.CharField('Уровень подготовки', choices=CATEGORY_TYPE, null=True, blank=True, max_length=20)
    rating = models.IntegerField('Рейтинг', null=True, default=0)
    previous_ratings = models.JSONField('Прошлые рейтинги', default=list)
    role = models.CharField('Роль', choices=TEAM_ROLE, null=True, blank=True, max_length=20)
    tg_chat_id = models.BigIntegerField(null=True)
    

    class Meta:
        verbose_name = 'Профиль пользователя'        
        verbose_name_plural = 'Профили пользователей' 
        permissions = [
            ("cant_reg_in_tour", "Cannot register in tournament"),
        ]

    def __str__(self):
        return f'{self.fullname} / {self.role}' 


class Competitor(models.Model):
    player_id = models.IntegerField('ID игрока', primary_key=True, unique=True, editable=False) 
    profile = models.OneToOneField(Profile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField('Имя', max_length=50)
    role = models.CharField('Роль', choices=TEAM_ROLE, default='forward', max_length=20)
    age = models.IntegerField('Возраст', null=True)
    gender = models.CharField('Пол', choices=GENDER_TYPE, default='M', max_length=20)

    rating = models.IntegerField('Рейтинг', null=True)
    start_rating = models.IntegerField(null=True)
    group_id = models.IntegerField('ID группы', null=True, blank=True)
    matches_played = models.IntegerField('Матчей сыграно', default=0)
    goals_scored = models.IntegerField('Забитые', default=0)
    goals_taken = models.IntegerField('Пропущенные', default=0)
    banned = models.BooleanField('Исключен', default=False  )   

    def save(self, *args, **kwargs):
        if not self.player_id:
            last_obj = Competitor.objects.order_by('-player_id').first()
            self.player_id = 1 if not last_obj else last_obj.player_id + 1
        super().save(*args, **kwargs)

    def __str__(self):
        return f"ID: {self.player_id}, {self.name}, {self.role}, {self.age}, сыграно: {self.matches_played} матчей, {self.rating}"
    
    class Meta:
        verbose_name = 'Участник'        
        verbose_name_plural = 'Участники' 
    

class Tournament(models.Model):
    tour_id = models.IntegerField('Номер турнира', primary_key=True, unique=True, editable=False)
    playing_groups_ids = models.JSONField('ID групп турнира', default=list)
    date = models.DateField('Дата', default=timezone.now)
    time_started = models.TimeField('Время начала', default=timezone.now)
    minutes_btwn_groups = models.IntegerField('Перерыв между группами (мин)', validators=[MinValueValidator(0)], default=10)
    minutes_btwn_matches = models.IntegerField('Перерыв между  матчами (мин)', validators=[MinValueValidator(0)], default=1)
    played_with_matrix = models.JSONField('Матрица встреч игроков', default=list)
    isEnded = models.BooleanField('Турнир закончен', default=False)

    class Meta:
        verbose_name = 'Турнир'        
        verbose_name_plural = 'Турниры' 
        permissions = [
            ("can_start_tour", "Can start new tournament"),
            ("can_shift_timetable", "Can shift timetable"),
        ]

    def save(self, *args, **kwargs):
        if not self.tour_id:
            last_obj = Tournament.objects.order_by('-tour_id').first()
            self.tour_id = 1 if not last_obj else last_obj.tour_id + 1
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Турнир №{self.tour_id} / {self.date.strftime('%d-%m-%Y')}"


class TournamentGroup(models.Model):
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE, related_name='groups')
    group_id = models.IntegerField('ID группы')
    group_age_pool = models.JSONField('Диапазон возраста', default=tuple)
    age_spread = models.IntegerField('Разброс по возрасту в матче', default=1)
    group_gender = models.CharField('Пол участников', max_length=20) 
    stopped_played = models.BooleanField('Закончила играть', default=False)

    def __str__(self):
        return f"Группа №{self.group_id}, {self.group_age_pool[0]}-{self.group_age_pool[1]} лет, {self.group_gender}"
    
    class Meta:
        verbose_name = 'Группа турнира'        
        verbose_name_plural = 'Группы турнира' 
   

class Micromatch(models.Model):
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE, null=True, related_name='matches')
    group_id = models.IntegerField('ID группы', null=True)
    match_id = models.UUIDField('ID матча', primary_key=True, default=uuid.uuid4, editable=False)
    matchRating = models.IntegerField('Средний рейтинг')
    players_ids = models.JSONField('ID игроков', default=list)
    team1_players = models.JSONField('Команда 1')
    team2_players = models.JSONField('Команда 2')
    team1_score = models.IntegerField('Счет первой команды', default=0)
    team2_score = models.IntegerField('Счет второй команды', default=0)
    isPlayed = models.BooleanField('Матч сыгран', default=False)
    start_time = models.TimeField('Время начала', default=timezone.now)
    field_num = models.IntegerField('Номер поля', default=1)

    class Meta:
        verbose_name = 'Микроматч'        
        verbose_name_plural = 'Микроматчи' 
        permissions = [
            ("can_save_score", "Can save match score"),
            ("can_generate_match", "Can generate new match"),
        ]

    def __str__(self):
        return f"Микроматч / время: {self.start_time.strftime('%H:%M')}"
    
    


class Announsment(models.Model):
    title = models.CharField('Заголовок', max_length=150)
    text = models.TextField('Текст', max_length=500)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = 'Объявление'        
        verbose_name_plural = 'Объявления'  

main_app/forms.py
from django import forms
import re
from django.contrib.auth import authenticate
from .models import Profile
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

class createUserForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = ""
        self.fields['password1'].error_messages = {
            'required': _('Пароль обязателен для заполнения'),  
        }
        
    username = forms.CharField(label='Username в telegram (без @)')
    password1 = forms.CharField(label='Придумайте пароль', widget=forms.TextInput)
    password2 = forms.CharField(label='Повторите пароль', widget=forms.TextInput)

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise ValidationError("Этот логин уже зарегистрирован в системе")
        return username

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
       

class profileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = ""

        self.fields['fullname'].widget.attrs.update({'placeholder': 'Иванов Иван Иванович'})
        self.fields['email'].widget.attrs.update({'placeholder': 'test@domain.ru'})
        self.fields['mobile_phone'].widget.attrs.update({'placeholder': '+79999999999'})

    def clean_fullname(self):
        fullname = self.cleaned_data['fullname']
        if len(fullname.split()) < 2:
            raise ValidationError("Введите полное ФИО")
        return fullname
    
    def clean_age(self):
        age = self.cleaned_data['age']
        if age < 6:
            raise ValidationError("Минимальный возраст - 6 лет")
        if age > 80:
            raise ValidationError("Проверьте указанный возраст")
        return age
    
    def clean_email(self):
        email = self.cleaned_data['email']
        if Profile.objects.filter(email=email).exists():
            raise ValidationError( "Этот email уже зарегистрирован")
        pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
        if not re.fullmatch(pattern, email):
            raise ValidationError("Введите корректный email адрес")
        return email

    def clean_mobile_phone(self):
        mobile_phone = self.cleaned_data['mobile_phone']
        if Profile.objects.filter(mobile_phone=mobile_phone).exists():
            raise ValidationError( "Этот телефон уже используется")
        if not mobile_phone.startswith('+7'):
            raise ValidationError("Введите номер, начинающийся с +7")
        if len(mobile_phone) != 12 or not mobile_phone[1:].isdigit():
            raise ValidationError("Номер должен содержать 11 цифр после +7")
        return mobile_phone

    class Meta:
        model = Profile
        fields = ['fullname', 'email', 'mobile_phone', 'gender', 'age', 'category', 'role']
        labels = {
            "fullname": "ФИО",
            "email": "Email",
            "mobile_phone": "Телефон",
            "gender": "Пол",
            "age": "Возраст",
            "category": "Разряд", 
            "role": "Роль"
        } 

class loginForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = ""
        
    username = forms.CharField(label='Username в telegram (без @)', max_length=100)
    password = forms.CharField(widget=forms.PasswordInput, label='Пароль', max_length=100)
    
    def clean(self):
        cleaned_data = super().clean()
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        user = authenticate(username=username, password=password)
        print(user)
        if user is None:
            raise ValidationError("Неверный логин или пароль")
        return cleaned_data
    
class chatBotForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = ""
        
    chat_id = forms.IntegerField(label='Введите ID чата (набор цифр)')

main_app/templates/home.html
{% extends 'pattern.html' %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static 'css/home-style.css' %}">
{% endblock %}

{% block title %}
<title>Объявления</title>
{% endblock %}

{% block content %}
<div class="container">
    <h3 class="announsments-title">Объявления</h3>
    <div class="line"></div>
    <section class="announsments-list">
        {% for announs in announs_list %}
            <div class="announsment">
                <h5>{{ announs.title }}</h5>
                <p>{{ announs.text }}</p>
            </div>             
        {% endfor %} 
    </section>
    <h3 class="timetable-title">Ближайшие турниры</h3>
    <section>

    </section>
</div>
{% endblock %}

main_app/templates/login.html
<h1>Выполните вход</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Войти</button>
</form>

main_app/templates/ratings.html
{% extends 'pattern.html' %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static 'css/ratings-style.css' %}">
    <script type="module" src="{% static 'js/rate-table-render.js' %}"></script> 
{% endblock %}

{% block title %}
<title>Рейтинг</title>
{% endblock %}

{% block content %}
    <div class="container">
        <h3>Рейтинг</h3>
        <div class="line"></div>    
        <section class="ratings-block">
            <div class="table-filter">
                <h4>Cортировать: </h4>
                <select class="filter">
                    <option value="-rating">---------</option>
                    <option value="M">Пол (сначала мужской)</option>
                    <option value="W">Пол (сначала женский)</option>
                    <option value="-age">Возраст (по убыванию)</option>
                    <option value="age">Возраст (по возрастанию)</option>
                </select>
            </div>
            <table class="table-headers-block"></table>
            <table class="table-rows"></table>  
        </section>
    </div>
{% endblock %}

main_app/templates/timetable.html
{% extends 'pattern.html' %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static 'css/timetable-style.css' %}">
    <script type="module" src="{% static 'js/timetable.js' %}"></script> 
{% endblock %}

{% block title %}
<title>Расписание</title>
{% endblock %}

{% block content %}
    <div class="container">
        <h3>Расписание</h3>
        <div class="line"></div>
        <section class="filter-groups">
            <h4>Группы:</h4>
            <select class="filter">
                <option value="0">Все группы</option>
                <option value="1">6-10 лет, мальчики</option>
                <option value="2">6-10 лет, девочки</option>
                <option value="3">11-15 лет, юноши</option>
                <option value="4">11-15 лет, девушки</option>
                <option value="5">16+ лет, мужская</option>
                <option value="6">16+ лет, женская</option>
            </select>
        </section>    
        <section class="timetable-block">
            <div class="timetable-matches"></div>
        </section>
    </div>
{% endblock %}

main_app/templates/tournaments.html
{% extends 'pattern.html' %}
{% load static %}

{% block link %}
<link rel="stylesheet" href="{% static 'css/tournaments-style.css' %}">
<script type="module" src="{% static 'js/main.js' %}"></script>
{% endblock %}

{% block title %}
<title>Турнир</title>
{% endblock %}

{% block content %}
<div class="container">
    <section id="start">
        <h3>Турнир</h3>
        <a href="#played" class="nav-page">Перейти к отыгранным матчам</a>
        <div class="line"></div>
        {% if user.is_authenticated %}
            {% if not perms.main_app.cant_reg_in_tour %}
            <section class="tournament-block">
                <div class="container">
                    <div class="tournament-register">
                        <h5 class="register-title">Нажмите на кнопку ниже, чтобы принять участие в турнире!</h5>
                        <span class="register-comment">Записываться нужно только игрокам!</span>
                        <a href="{% url 'register_to_tour' %}"><button class="register-btn">Участвовать</button></a>
                    </div>
                </div>
            </section>
            {% endif %}
        {% endif %}
        <div class="tour-controls">
            {% if perms.main_app.can_generate_tour %}
                <div class="tour-generation">
                    <h4>Создание турнира:</h4>
                    <button class="generate-btn">Создать расписание</button>
                </div>
            {% endif %}
            {% if perms.main_app.can_shift_timetable %}
                <div class="shift-time">
                    <h4>Сдвинуть время матчей:</h4>
                    <button class="shift-btn">Указать время</button>
                </div>
            {% endif %}
        </div>
    </section>
    <section>
        <div class="matches">
            <div class="loading">
                <h4>Обработка данных</h4>
                <span class="loader"></span>
            </div>
        </div>
    </section>
    <section id="played">
        <h3>Отыгранные матчи</h3>
        <a href="#start" class="nav-page">Вернуться в начало страницы</a>
        <div class="line"></div>
        <div class="played-matches">
        </div>
    </section>
    <div id="overlay"></div>
    <section>
        <div class="modal-edit">
            <h3>Настройки турнира</h3>
            <span class="form-error"></span>
            <a class="modal-close">
                <svg fill="#000000" width="20px" height="20px" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
    <path d="M0 14.545L1.455 16 8 9.455 14.545 16 16 14.545 9.455 8 16 1.455 14.545 0 8 6.545 1.455 0 0 1.455 6.545 8z" fill-rule="evenodd"/>
</svg>
            </a>
            <form method="POST" class="edit-form">
                {% csrf_token %}
                <div>
                    <p>Время начала: </p>
                    <input id="start-time" type="text" pattern="^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$" placeholder="например, 17:00">
                </div>
                <div>
                    <p>Уровень подготовки:</p>
                    <div id="category" class="multiselect-checkbox">
                        <label><input type="checkbox" name="options" value="1"> 6-10 лет, мальчики</label>
                        <label><input type="checkbox" name="options" value="2"> 6-10 лет, девочки</label>
                        <label><input type="checkbox" name="options" value="3"> 11-15 лет, юноши</label>
                        <label><input type="checkbox" name="options" value="4"> 11-15 лет, девушки</label>
                        <label><input type="checkbox" name="options" value="5"> 16+ лет, мужская</label>
                        <label><input type="checkbox" name="options" value="6"> 16+ лет, женская</label>
                    </div>
                </div>
                
                <div>
                    <p>Перерыв между группами (в минутах):</p>
                    <input id="group-delay" type="number" min="1">
                </div>
                <div>
                    <p>Перерыв между матчами (в минутах):</p>    
                    <input id="match-delay" type="number" min="0">
                </div>
                <button type="button" class="modal-save-btn">Начать турнир</button>
            </form>
        </div>
        <div class="modal-time-edit">
            <h3>Задайте время</h3>
            <span class="shift-form-error"></span>
            <a class="modal-time-close">
                <svg fill="#000000" width="20px" height="20px" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
    <path d="M0 14.545L1.455 16 8 9.455 14.545 16 16 14.545 9.455 8 16 1.455 14.545 0 8 6.545 1.455 0 0 1.455 6.545 8z" fill-rule="evenodd"/>
</svg>
            </a>
            <form method="POST" class="edit-form">
                {% csrf_token %}
                <h5>Укажите в минутах, введите отрицательное число (-10) для сдвига назад и положительное (10), чтобы сдвинуть вперед</h5>
                <div>
                    <p>Сдвинуть несыгранные на:</p>
                    <input id="matches-shift" type="number">
                </div>
                <button type="button" class="modal-shift-btn">Подвинуть матчи</button>
            </form>
        </div>
    </section>
</div>
{% endblock %}

main_app/templates/user_profile.html
{% extends 'pattern.html' %}
{% load static %}

{% block link %}
<link rel="stylesheet" href="{% static 'css/elements-style.css' %}">
<link rel="stylesheet" href="{% static 'css/timetable-style.css' %}">
<link rel="stylesheet" href="{% static 'css/profile-style.css' %}">
<script type="module" src="{% static 'js/profile.js' %}"></script> 
{% endblock %}

{% block title %}
<title>Личный кабинет</title>
{% endblock %}

{% block content %}
<div class="container">
    <h3>Ваш профиль</h3>
</div>
<section class="user-card-section">
    <div class="container">
        <div class="user-card">
            <div class="user-fullname">
                <img class="user-avatar" data-user-id="{{ user_id }}" src="{% static 'images/user-avatar.png' %}">
                <p>{{ profile.fullname }}</p>
            </div>
            <div class="user-info">
                <div class="user-info-items">
                    <div class="user-role">
                        <p><b>{{ profile.get_role_display }}</b></p>
                    </div>
                    <p>Email: <b>{{ profile.email }}</b></p>
                    <p>Телефон: <b>{{ profile.mobile_phone }}</b></p>
                    <p>Возраст: <b>{{ profile.age }}</b></p>
                    <p>Уровень подготовки: <b>{{ profile.category }}</b></p>
                    <p>Рейтинг игрока: <b>{{ profile.rating }}</b></p>
                    <p>ID игрока: <b><ins>{{ comp_id }}</ins></b></p>
                </div>
                <a class="profile-edit">Редактировать профиль</a>
                <a class="bot" href="{% url 'get_chatID' user.id  %}">БОТ</a>
            </div>
        </div>
    </div>
</section>
<section>
    <div class="container">
        <h3>Предыдущие 10 значений рейтинга</h3>
        <div class="last-ratings">
            {% for rating in profile.previous_ratings %}
                <span class="last-rating">{{ rating }}</span>
            {% endfor %}
        </div>
    </div>
</section>
<section>
    <div class="container">
        <h3>Ваши следующие матчи</h3>
        <div class="timetable-matches"></div>
    </div>
</section>
<div id="overlay"></div>
<section>
    <div class="container">
        <div class="modal-edit">
            <h3>Редактирование профиля</h3>
            <span class="form-error"></span>
            <a class="modal-close">
                <svg fill="#000000" width="20px" height="20px" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
    <path d="M0 14.545L1.455 16 8 9.455 14.545 16 16 14.545 9.455 8 16 1.455 14.545 0 8 6.545 1.455 0 0 1.455 6.545 8z" fill-rule="evenodd"/>
</svg>
            </a>
            <form method="POST" class="edit-profile-form">
                {% csrf_token %}
                <div>
                    <p>Email</p>
                    <input id="email" type="email" pattern='[^@\s]+@[^@\s]+\.[^@\s]+' placeholder="test@mail.ru">
                </div>
                <div>
                    <p>Телефон</p>
                    <input id="phone" type="tel" pattern='\+7\d{10}' placeholder="+79999999999">
                </div>
                <div>
                    <p>Возраст</p>
                    <input id="age" type="number" min="6" max="80">
                </div>
                <div class="edit-form-selectors">
                    <div>
                    <p>Уровень подготовки</p>
                    <select id="category" class="modal-select-category">
                        <option value="новичок">новичок</option>
                        <option value="любитель">любитель</option>
                        <option value="III юношеский">III юношеский</option>
                        <option value="II юношеский">II юношеский</option>
                        <option value="I юношеский">I юношеский</option>
                        <option value="III спортивный">III спортивный</option>
                        <option value="II спортивный">II спортивный</option>
                        <option value="I спортивный">I спортивный</option>
                        <option value="КМС">КМС</option>
                        <option value="ГР">ГР</option>
                        <option value="МСМК">МСМК</option>
                    </select>
                </div>
                <div>
                    <p>Роль</p> 
                    <select id="role" class="modal-select-role">
                        <option value="forward">нападающий</option>
                        <option value="defender">защитник</option>
                        <option value="goalkeeper">вратарь</option>
                    </select>
                </div>
                </div>
                <button type="button" class="modal-save-btn">Готово</button>
            </form>
        </div>
    </div>
</section>
{% endblock %}